version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      FLASK_SECRET_KEY: supersecret
      DB_HOST: your-db-host-ip
      DB_NAME: project1_db
      DB_USER: postgres
      DB_PASS: 1234
    restart: always
